spring.application.name=shop
server.port=2525

# Data source config
spring.datasource.url = 
spring.datasource.username = 
spring.datasource.password = 
spring.datasource.driver-class-name = 

# Enable sql script for table creation
# spring.sql.init.mode = ALWAYS

# show sql queries in console
spring.jpa.show-sql = true
 
# SQL initialization platform - specifies that database is mysql
spring.sql.init.platform = mysql
